- include: "prepare_nodes_for_introspection.yml"
  tags: instack

- name: register our hosts to instack
  shell: "source ~/stackrc; openstack baremetal import --json {{ instack_file }}"

- include: "ovb.yml"
  when: "'bmc' in groups"

- name: assign the kernel and ramdisk before introspection begins
  shell: "source ~/stackrc; openstack baremetal configure boot"

- name: start node introspection
  shell: "source ~/stackrc; openstack baremetal introspection bulk start"
  register: introspection_result
  failed_when: introspection_result.rc != 0
